name: Schedule Devbox images builds

# GitHub variables:
# - (inherit from matrix-build.yml)

# GitHub secrets:
# - (inherit from matrix-build.yml)

on:

  # Run on schedule
  schedule:
    # Daily at 2 AM, 8 AM, 2 PM, and 8 PM (UTC)
    - cron: '0 2/6 * * *'

  # Run on manual triggers
  workflow_dispatch:
    inputs:
      skip_published_tags:
        description: 'Skip tags already published to the registry. Disable to force rebuild of published tags.'
        type: boolean
        required: false
        default: true

# Set default GITHUB_TOKEN permissions for the workflow
permissions:
  contents: read

# Set workflow concurrency rules
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# Set environment variables for the workflow
env:
  IMAGES_LIST_YAML: |
    # Devbox Python
    - images_prefix: devbox-python
      src_dirname: python
      package_versions: python?
      base_variants: '["", "slim", "alpine"]'
    - images_prefix: devbox-python
      src_dirname: python
      package_versions: python?,poetry
      base_variants: '["", "slim", "alpine"]'
    - images_prefix: devbox-python
      src_dirname: python
      package_versions: python?,uv
      base_variants: '["", "slim", "alpine"]'
    # Devbox Python + Node
    - images_prefix: devbox-python-node
      src_dirname: python
      package_versions: python?,node?,nvm
      base_variants: '["", "slim"]'
    - images_prefix: devbox-python-node
      src_dirname: python
      package_versions: python?,node?,nvm,poetry
      base_variants: '["", "slim"]'
    - images_prefix: devbox-python-node
      src_dirname: python
      package_versions: python?,node?,nvm,uv
      base_variants: '["", "slim"]'

jobs:

  # Prepare job
  prepare:
    name: Cache package versions and published tags

    # https://github.com/actions/runner-images/blob/main/images/ubuntu-slim/ubuntu-slim-Readme.md
    runs-on: ubuntu-slim
    timeout-minutes: 10

    # Set GITHUB_TOKEN permissions for the job
    permissions:
      contents: read
      packages: read

    # Set environment variables for the job
    env:
      GITHUB_READ_TOKEN: ${{ secrets.GITHUB_READ_TOKEN }}

    outputs:
      matrix: ${{ steps.outputs.outputs.matrix }}

    steps:

      # Initialization steps

      - name: Checkout
        uses: actions/checkout@v6

      # Dependency steps

      - name: Install jq
        run: |
          # apt-get install jq
          sudo apt-get -q update
          sudo apt-get -qy install --no-install-recommends jq

      - name: Install yq
        env:
          YQ_VERSION: v4.53.3
          YQ_ARCH: linux_amd64
        run: |
          # Install yq
          sudo curl -SL \
            "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_${YQ_ARCH}" \
            -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      # Preparation steps

      - name: Set images list
        env:
          IMAGES_LIST_YAML: ${{ env.IMAGES_LIST_YAML }}
        run: |
          # Set IMAGES_LIST environment variable

          # Load helper scripts
          . ./.github/workflows/scripts/set_github_env.sh

          # Convert matrix strategy from YAML to JSON
          IMAGES_LIST="$(
            yq -o=json e '.' <<< "${IMAGES_LIST_YAML}"
          )"

          set_github_env 'IMAGES_LIST' "${IMAGES_LIST}" non-optional non-secret verbose

      - name: Set packages list
        env:
          IMAGES_LIST: ${{ env.IMAGES_LIST }}
        run: |
          # Set PACKAGES environment variable

          # Load helper scripts
          . ./.github/workflows/scripts/set_github_env.sh

          # Extract unique package names from the matrix JSON, ignoring unlabeled flags ('?')
          PACKAGES="$(
            jq -rc '
              .
              | map(.package_versions // "")
              | map(split(","))
              | add
              | map(sub("\\?$"; ""))
              | unique
              | .[]
            ' <<< "$IMAGES_LIST"
          )"

          set_github_env 'PACKAGES' "${PACKAGES}" non-optional non-secret verbose

      - name: Set images list
        env:
          IMAGES_LIST: ${{ env.IMAGES_LIST }}
        run: |
          # Set IMAGES_PREFIXES environment variable

          # Load helper scripts
          . ./.github/workflows/scripts/set_github_env.sh

          # Extract unique image prefixes from the matrix JSON
          IMAGES_PREFIXES="$(
            jq -rc '
              .
              | map(.images_prefix // "")
              | unique
              | .[]
            ' <<< "$IMAGES_LIST"
          )"

          set_github_env 'IMAGES_PREFIXES' "${IMAGES_PREFIXES}" non-optional non-secret verbose

      # Execution steps

      - name: Install deps
        run: |
          uv sync --frozen

      - name: Detect all package versions
        env:
          PACKAGES: ${{ env.PACKAGES }}
        run: |
          # Detect versions for each specified package
          while IFS= read -r package; do
            echo "Detecting versions for package '${package}'..."
            uv run python -m scripts.detect_versions "${package}" || true
          done <<< "${PACKAGES}"

      - name: Fetch all published tags
        if: ${{ inputs.skip_published_tags == true }}
        env:
          GITHUB_READ_TOKEN: ${{ secrets.GITHUB_READ_TOKEN }}
          IMAGES_PREFIXES: ${{ env.IMAGES_PREFIXES }}
        run: |
          # Fetch published tags for each specified image prefix

          # Get datetime of last commit in the repository
          LAST_COMMIT_DATETIME="$(git log -1 --format=%cI)"

          while IFS= read -r image_prefix; do

            echo "Fetching published tags for image prefix '${image_prefix}'..."
            uv run python -m scripts.fetch_published_tags \
              --ignore-tags-older-than "${LAST_COMMIT_DATETIME}" \
              "${image_prefix}" \
              || true

          done <<< "${IMAGES_PREFIXES}"

      - name: Compute build matrix
        env:
          IMAGES_LIST: ${{ env.IMAGES_LIST }}
        run: |
          # Compute build matrix based on the strategy matrix

          # Load helper scripts
          . ./.github/workflows/scripts/set_github_env.sh

          # Iterate over each combination in the strategy matrix
          while read -r matrix_entry; do

            # Extract package_versions and base_variants from the matrix entry
            images_prefix="$(jq -r '.images_prefix // ""' <<< "${matrix_entry}")"
            src_dirname="$(jq -r '.src_dirname // ""' <<< "${matrix_entry}")"
            package_versions="$(jq -r '.package_versions // ""' <<< "${matrix_entry}")"
            base_variants="$(jq -r '.base_variants // "[]"' <<< "${matrix_entry}")"

            # Skip if package_versions is empty
            if [ -z "${package_versions}" ]; then
              continue
            fi

            # List specified package names in a comma-separated format
            # Keep unlabeled flags ('?'), drop specified package versions
            packages="$(
              echo "${package_versions}" \
              | sed 's/,/\n/g' \
              | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' \
              | sed 's/=.*$//' \
              | grep -v '^$' \
              | tr '[:upper:]' '[:lower:]' \
              | paste -sd ',' -
            )"

            # Skip if packages list is empty
            if [ -z "${packages}" ]; then
              continue
            fi

            common_metadata="$(
              jq -n \
                --arg images_prefix "${images_prefix}" \
                --arg src_dirname "${src_dirname}" \
                '{
                  images_prefix: $images_prefix,
                  src_dirname: $src_dirname
                }'
              )"

            # Compute & append build matrix for specified packages
            uv run python -m scripts.build_matrix --append \
              --common-metadata "${common_metadata}" \
              --base-variants "${base_variants}" \
              "${packages}"

          done <<< "$(jq -c '.[]' <<< "${IMAGES_LIST}")"

      - name: Randomly sample build matrix subset
        run: |
          # Randomly sample a subset of builds to run from the build matrix
          # Set BUILD_MATRIX environment variable

          # Load helper scripts
          . ./.github/workflows/scripts/set_github_env.sh

          # Transform list of build matrix entries
          # to job matrix configuration in JSON format.
          # Randomly sample a subset of 10 builds to run from the build matrix.
          BUILD_MATRIX="$(
            yq -o=json e '.build_matrix' ./dist/build_matrix.yml \
            | jq -c '.[]' \
            | shuf -n 10 \
            | jq -rcs '{ include: . }'
          )"

          set_github_env 'BUILD_MATRIX' "${BUILD_MATRIX}" non-optional non-secret verbose

      - name: Set job outputs
        id: outputs
        env:
          BUILD_MATRIX: ${{ env.BUILD_MATRIX }}
        run: |
          # Set job output variables

          # Load helper scripts
          . ./.github/workflows/scripts/set_github_output.sh

          set_github_output 'matrix' "${BUILD_MATRIX}" non-optional verbose

  # Run build for each matrix entry
  build-push:
    name: Run build & push

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    # Job dependencies
    needs:
      - prepare

    # Set GITHUB_TOKEN permissions for the job
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-push.yml
    with:
      images_prefix: ${{ matrix.images_prefix }}
      src_dirname: ${{ matrix.src_dirname }}
      image_tag_components: ${{ matrix.image_tag_components }}
      build_args: ${{ matrix.build_args }}
    secrets: inherit
